elasticsearch:
  host: hpc3-20-11 # default: please don't change this if not necessary
  port: 9200 # default: please don't change this if not necessary
#  index_name: bench4bl_3 # NECESSARY: change this to your index name.
#  index_name: bench4bl_full # NECESSARY: change this to your index name.
  index_name: ghrb_full_100_2 # NECESSARY: change this to your index name.
#  index_name: bench4bl_full_100 # NECESSARY: change this to your index name.

Fields:
  project: keyword
  buggy_commit: keyword
  source_code: text
  file_url: keyword
  bug_id: keyword
#  bug_id: keyword
#  bug_summary: text
#  bug_description: text
